### PR TITLE
Create help

### PR DESCRIPTION
**Pull request by maki18o**
Hi I have a problem using your mdt. It is showin the lastName/firstName could be found and I cannot realy do much do you know who to repair that?

### CODE REVIEW

**Comment by cowardtv** [comment]
what esx version you use?

**Comment by maki18o** [comment]
'1.1.0'

**Comment by cowardtv** [comment]
the mdt is fit for legacy you need to change it... i have 1.1 as well but i dont know how to pull request to share

**Comment by maki18o** [comment]
i think below here you can upload filles of you could upload 1.1 I would be realy gratefull

**Comment by cowardtv** [comment]
[mdt.zip](https://github.com/DarkloaderTM/mdt/files/7613944/mdt.zip)
just change the coward to esx and you should be fine

**Comment by maki18o** [comment]
it is showing me the sv server file error at line 10

**Pull request closed without merging**
